export {
	CURVE_ENDPOINT_EPSILON,
	CURVE_FLATNESS_TOLERANCE,
	CURVE_MAX_SAMPLE_SPAN,
	CURVE_SELF_INTERSECTION_TOLERANCE,
	cubicBezierDerivative,
	cubicBezierPoint,
	pointAtDistance,
	projectPointToSampledSegment,
	sampleSegment,
	sampledPolylineIntersects,
	sampledPolylineSelfIntersects,
	segmentLength,
	segmentPointAt,
	segmentTangentAt,
	type CubicBezierShape,
	type CurveDistanceResult,
	type CurveSample,
	type SampledSegment
} from '$lib/layout/layout-geometry-curve';
