export {
  CHOPIN_LAYOUT_CEILING_THICKNESS,
  CHOPIN_LAYOUT_FALLBACK_FLOOR_NAME,
  CHOPIN_LAYOUT_FLOOR_ID,
  CHOPIN_LAYOUT_FLOOR_THICKNESS,
  CHOPIN_LAYOUT_WALL_THICKNESS,
  roomsToLayout
} from '$lib/content/rooms-to-layout';
